name: travel_xp
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Ensure the version constraint is a string
  flutter: ">=3.0.0 <4.0.0"  # Corrected version constraint

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1  # for Firebase Authentication (optional)
  cloud_firestore: ^5.4.3  # for Firestore (optional)
  firebase_storage: ^12.3.2  # for Firebase Storage (optional)

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
